[project]
name = "chrono-python"
version = "2.0.0.dev0"
description = "A natural language date parser."
readme = "README.md"
requires-python = ">=3.12"
authors = [
    { name = "Wanasit Tanakitrungruang" }
]
dependencies = []

[dependency-groups]
dev = [
    "pytest>=7.4.4",
]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.pytest.ini_options]
log_level = "DEBUG"